fieldHeight: 100
fieldWidth: 20
plantsMaxQuantityForCell: 200
plantQuantity: 1000
plantLiveTime: 10
simulationDuration: 360
animalConfigurations:
    -   className: "Wolf"
        name: "ğŸº"
        weight: 50.0
        maxQuantityForCell: 30
        speed: 3
        fullSatietyWeight: 8
        currentHungryPercent: 100
    -   className: "Fox"
        name: "ğŸ¦Š"
        weight: 8.0
        maxQuantityForCell: 30
        speed: 2
        fullSatietyWeight: 2
        currentHungryPercent: 100
    -   className: "Eagle"
        name: "ğŸ¦…"
        weight: 6.0
        maxQuantityForCell: 20
        speed: 3
        fullSatietyWeight: 1
        currentHungryPercent: 100
    -   className: "Boa"
        name: "ğŸ"
        weight: 15.0
        maxQuantityForCell: 30
        speed: 1
        fullSatietyWeight: 3
        currentHungryPercent: 100
    -   className: "Bear"
        name: "ğŸ»"
        weight: 500.0
        maxQuantityForCell: 5
        speed: 2
        fullSatietyWeight: 80
        currentHungryPercent: 100
    -   className: "Sheep"
        name: "ğŸ‘"
        weight: 70.0
        maxQuantityForCell: 140
        speed: 3
        fullSatietyWeight: 15
        currentHungryPercent: 100
    -   className: "Rabbit"
        name: "ğŸ‡"
        weight: 2.0
        maxQuantityForCell: 150
        speed: 2
        fullSatietyWeight: 0.45
        currentHungryPercent: 100
    -   className: "Mouse"
        name: "ğŸ"
        weight: 0.05
        maxQuantityForCell: 500
        speed: 1
        fullSatietyWeight: 0.01
        currentHungryPercent: 100
    -   className: "Horse"
        name: "ğŸ"
        weight: 400.0
        maxQuantityForCell: 20
        speed: 4
        fullSatietyWeight: 60
        currentHungryPercent: 100
    -   className: "Goat"
        name: "ğŸ"
        weight: 60.0
        maxQuantityForCell: 140
        speed: 3
        fullSatietyWeight: 10
        currentHungryPercent: 100
    -   className: "Duck"
        name: "ğŸ¦†"
        weight: 1.0
        maxQuantityForCell: 200
        speed: 4
        fullSatietyWeight: 0.15
        currentHungryPercent: 100
    -   className: "Deer"
        name: "ğŸ¦Œ"
        weight: 300.0
        maxQuantityForCell: 20
        speed: 4
        fullSatietyWeight: 50
        currentHungryPercent: 100
    -   className: "Caterpillar"
        name: "ğŸ›"
        weight: 0.01
        maxQuantityForCell: 1000
        speed: 0
        fullSatietyWeight: 0
        currentHungryPercent: 100
    -   className: "Buffalo"
        name: "ğŸƒ"
        weight: 700.0
        maxQuantityForCell: 10
        speed: 3
        fullSatietyWeight: 100
        currentHungryPercent: 100
    -   className: "Boar"
        name: "ğŸ—"
        weight: 400.0
        maxQuantityForCell: 50
        speed: 2
        fullSatietyWeight: 50
        currentHungryPercent: 100
